### PR TITLE
Add ELB tags

### PR DESCRIPTION
**Pull request by wstrucke**

### CODE REVIEW

**Comment by wstrucke** [comment]
Hi!  This patch has been working in our environment for a number of months but I recall now why I delayed in sending a pull request.  It adds substantial load to the AWS API due to querying for tags on every ELB individually.  I plan on altering it to perform batch requests to Amazon but haven't gotten around to implementing that yet.

**Comment by brharrington** [comment]
Might also be useful to have an option to disable it. Then users could choose if they want to have the additional calls.

**Comment by hridyeshpant** [comment]
@bradbenvenuti @wstrucke there are two new pull request, both are related to ELB.
https://github.com/Netflix/edda/pull/117 --> adding pagination for elb crawler
https://github.com/Netflix/edda/pull/112  --> Add support for elbv2
If someone can review/merge all these in single pull request, that will be great.

**Comment by hridyeshpant** [comment]
@wstrucke thanks for adding ELB tag part.
could you pick the latest code which has "pagination for elb crawler"
#117 --> adding pagination for elb crawler
Also could you address @brharrington comments as well?

**Comment by brharrington** [comment]
An option to disable the querying of tags can come later if someone has the time to create a PR. Minor changes have been addressed and conflicts resolved with master branch.

**Pull request merged**
