### PR TITLE
add build tasks

### PR DESCRIPTION
**Pull request by wstrucke**
adding build tasks and restoring log4j; this puts log4j in the war file I'm deploying.  if there is a better way to do this I'm all ears.

### CODE REVIEW

**Comment by wstrucke** [comment]
I don't know that the Travis build failure is related to this commit.

**Comment by brharrington** [comment]
At first glance it doesn't look related. Might be some issue with the build, I found a few areas where the build is flakey, but haven't had time to debug them. The error in that build doesn't look familiar though.

**Comment by wstrucke** [comment]
Could it be due to memory limits in travis?  I've seen a similar problem in jenkins due to the configured job limits.

**Comment by brharrington** [comment]
Build failures appear to have been due to a corrupt cache. I cleared all of the travis caches and the build succeeded.

**Pull request merged**
